import fs from 'node:fs';
const doc=fs.readFileSync('docs/ASYMMETRIC_RANK_PROTOTYPE.md','utf8');
const road=fs.readFileSync('ROADMAP.md','utf8');
const html=fs.readFileSync('index.html','utf8');
function ok(v,m){if(!v)throw new Error(m);console.log(`PASS: ${m}`)}
const start=doc.indexOf('## 비대칭 네임드 샘플 12장');
const end=doc.indexOf('### 샘플 풀 감사 기준',start);
ok(start>=0&&end>start,'prototype doc contains the 12-card asymmetric sample section');
const sample=doc.slice(start,end);
const rows=sample.split('\n').filter(line=>/^\|\s*(?:A|[2-9]|10|J|Q|K)[♠♥♦♣]\s*\|/.test(line));
ok(rows.length===12,'sample pool contains exactly 12 candidate cards');
const rankValue={A:1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'10':10,J:11,Q:12,K:13};
const parsed=rows.map(line=>{const c=line.split('|').slice(1,-1).map(x=>x.trim());const slot=c[0],printed=c[1],tier=c[2],name=c[3],effect=c[4];const base=slot.replace(/[♠♥♦♣]$/,'');const [a,b]=printed.split('/');return{slot,base,a,b,tier,name,effect,delta:Math.abs(rankValue[a]-rankValue[b])}});
ok(new Set(parsed.map(x=>x.slot)).size===12,'all sample candidates occupy distinct canonical slots');
ok(parsed.every(x=>x.a===x.base||x.b===x.base),'every asymmetric sample preserves its baseRank on one printed side');
const counts=Object.fromEntries(['소','중','대','극단'].map(t=>[t,parsed.filter(x=>x.tier===t).length]));
ok(Object.values(counts).every(n=>n===3),'sample pool distributes three cards into each flexibility tier');
ok(parsed.filter(x=>x.tier==='소').every(x=>x.delta>=1&&x.delta<=2),'small tier stays within delta 1-2');
ok(parsed.filter(x=>x.tier==='중').every(x=>x.delta>=3&&x.delta<=4),'medium tier stays within delta 3-4');
ok(parsed.filter(x=>x.tier==='대').every(x=>x.delta>=5&&x.delta<=6),'large tier stays within delta 5-6');
ok(parsed.filter(x=>x.tier==='극단').every(x=>x.delta>=7),'extreme tier stays at delta 7+');
const high=parsed.filter(x=>x.tier==='대'||x.tier==='극단');
ok(high.every(x=>/(보내야|고정|봉인|버려야|선택할 수 없다)/.test(x.effect)),'every delta 5+ sample carries an explicit tempo cost, restriction, or penalty');
ok((sample.match(/누적 위력이 6 증가/g)||[]).length===1,'only one of twelve samples directly increases SWITCH power');
ok(sample.includes('`레드라인 기어`'),'the single direct-power sample is Redline Gear');
ok(doc.includes('#### 권장 등장 등급 — 아직 런타임 미구현'),'rarity guidance is documented as design metadata only');
ok(doc.includes('`소` — 일반 후보')&&doc.includes('`중` — 고급 후보')&&doc.includes('`대` — 희귀 후보')&&doc.includes('`극단` — 특수·이벤트 후보'),'all four flexibility tiers have future reward-pool guidance');
ok(doc.includes('현재 게임에 새 희귀도 시스템을 추가하는 것이 아니라'),'rarity guidance does not create a live runtime system');
ok(doc.includes('일반 네임드 `X/X`는 비대칭 유연성 세금을 내지 않으므로')&&doc.includes('`PURE X/X`는 전투 효과 경쟁이 아니라'),'PURE and regular X/X maintenance-value principles are recorded');
ok(doc.includes('실제 `NAMED` 승격은 M11B 밸런스 표본 전에 하지 않는다'),'sample cards are explicitly blocked from live promotion before balance evidence');
const namedStart=html.indexOf('const NAMED={'),namedEnd=html.indexOf('const FIELDS=',namedStart),namedBlock=html.slice(namedStart,namedEnd);
ok(!/topRank\s*:|bottomRank\s*:/.test(namedBlock),'live NAMED pool still contains zero asymmetric definitions');
ok(road.includes('- [x] 비대칭값을 실제로 활용하는 네임드 효과 샘플 10~20장 설계'),'ROADMAP closes the asymmetric sample-card design item');
ok(road.includes('- [x] 숫자 차이가 큰 카드가 단순 상위호환이 되지 않도록 효과 예산 / 희귀도 / 패널티 기준 수립'),'ROADMAP closes the flexibility budget/rarity/penalty item');
ok(road.includes('- [x] 순수 `X/X` 카드와 일반 네임드 `X/X`가 비대칭 `X/Y` 카드와 경쟁할 수 있는 유지 가치 설계'),'ROADMAP closes the X/X maintenance-value item');
console.log('M11B asymmetric sample/budget regression passed.');
