from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

def replace_once(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing patch target: {label}')
    s=s.replace(old,new,1)

old_on="""function onDiscardDraw(w,c){if(!c)return;if(c.blockedUntilTurn===state.turnNo){log(`${c.name}: 쥐구멍 페널티로 이번 턴 조합에 사용할 수 없습니다.`,'hit')}if(c.tag==='bait'&&c.originOwner!==w){const own=sideObj(c.originOwner);drawOne(c.originOwner,false);const cand=own.hand.filter(x=>x.uid!==c.uid).sort((a,b)=>b.age-a.age)[0];if(cand){removeFromHand(c.originOwner,[cand]);own.deck.unshift(cand)}log(`${c.name}: 원주인이 1장 순환.`,'good')}if(c.tag==='discardContract')c.contractActive=true;if(c.tag==='smuggledSuit'){c.smuggledTurnToken=state.turnToken;c.smuggledActive=false}if(c.tag==='fencePeek'){const below=state.discard.at(-1);if(below)log(w==='player'?`${c.name}: 아래 카드 확인 · ${cardText(below)}${below.named?' ['+below.name+']':''}.`:`${c.name}: CPU가 버림패 아래 카드를 확인했습니다.`,'important')}if(c.tag==='appraiser'){let count=0;for(const side of [w,other(w)])for(const m of meldsOf(side))if(meldType(m.cards.concat(c))===m.type)count++;if(count>=2)addShield(w,3)}}"""
new_on="""function bottomSpecificHandCard(w,c,label='순환'){const side=sideObj(w),i=side.hand.findIndex(x=>x.uid===c?.uid);if(i<0)return false;const[chosen]=side.hand.splice(i,1);chosen.fromDiscard=false;chosen.contractActive=false;chosen.age=0;side.deck.unshift(chosen);log(`${label}: ${w==='player'?'내':'상대'} ${cardText(chosen)}를 덱 아래로 보냈습니다.`,'good');if(w==='player')flashPile('deckPile');return true}
function requestHandBottomChoice(w,opts={}){const side=sideObj(w),exclude=new Set((opts.exclude||[]).map(c=>c.uid)),candidates=side.hand.filter(c=>!exclude.has(c.uid));if(!candidates.length){if(typeof opts.onAsyncResolved==='function')opts.onAsyncResolved(null);return false}const apply=c=>bottomSpecificHandCard(w,c,opts.label||opts.title||'순환'),interactive=w==='player'&&typeof requestEffectChoice==='function'&&candidates.length>1;if(interactive){return requestEffectChoice({title:opts.title||'손패 선택',text:opts.text||'덱 아래로 보낼 손패 1장을 고르세요.',options:candidates.map(c=>({key:c.uid,label:`${cardText(c)}${c.named?` · ${c.name}`:''}`,detail:`보유 ${c.age}턴`,card:c})),onChoose:o=>{if(o?.card)apply(o.card);if(typeof opts.onAsyncResolved==='function')opts.onAsyncResolved(o?.card||null)}})}apply([...candidates].sort((a,b)=>b.age-a.age)[0]);return false}
function onDiscardDraw(w,c,opts={}){if(!c)return false;if(c.blockedUntilTurn===state.turnNo){log(`${c.name}: 쥐구멍 페널티로 이번 턴 조합에 사용할 수 없습니다.`,'hit')}if(c.tag==='bait'&&c.originOwner!==w){const owner=c.originOwner;drawOne(owner,false);const paused=requestHandBottomChoice(owner,{title:c.name,label:c.name,text:'미끼를 상대가 가져갔습니다. 1장 뽑은 뒤 덱 아래로 보낼 내 손패 1장을 고르세요.',onAsyncResolved:()=>{log(`${c.name}: 원주인이 1장 순환.`,'good');if(typeof opts.onAsyncResolved==='function')opts.onAsyncResolved()}});if(paused)return true;log(`${c.name}: 원주인이 1장 순환.`,'good')}if(c.tag==='discardContract')c.contractActive=true;if(c.tag==='smuggledSuit'){c.smuggledTurnToken=state.turnToken;c.smuggledActive=false}if(c.tag==='fencePeek'){const below=state.discard.at(-1);if(below)log(w==='player'?`${c.name}: 아래 카드 확인 · ${cardText(below)}${below.named?' ['+below.name+']':''}.`:`${c.name}: CPU가 버림패 아래 카드를 확인했습니다.`,'important')}if(c.tag==='appraiser'){let count=0;for(const side of [w,other(w)])for(const m of meldsOf(side))if(meldType(m.cards.concat(c))===m.type)count++;if(count>=2)addShield(w,3)}return false}"""
replace_once(old_on,new_on,'off-turn hand bottom helper + bait pause')

old_ai="""function aiTurn(){if(state.gameOver)return;turnStart('enemy');state.turn='enemy';state.phase='wait';state.lastEnemyUsedDiscard=false;const acquisition=prepareAcquisitionPhase('enemy');if(state.gameOver){render();return}let fromDiscard=false,top=state.discard.at(-1);if(!state.enemy.blockOpponentDiscardNext&&top&&discardHelpsAI(top))fromDiscard=true;let c=null;if(acquisition==='draw'){if(fromDiscard&&state.field?.tag==='blackMarket'&&state.discard.length>=2){const a=state.discard.at(-1),b=state.discard.at(-2);if(aiCardChoiceScore(b)>aiCardChoiceScore(a)){const rm=state.discard.pop();sideObj(rm.owner).spent.push(rm);c=acquireDiscardCard('enemy',0)}else c=drawOne('enemy',true)}else c=fromDiscard?drawOne('enemy',true):drawOne('enemy',false)}if(state.enemy.blockOpponentDiscardNext)state.enemy.blockOpponentDiscardNext=false;state.lastEnemyUsedDiscard=fromDiscard;if(c){log(fromDiscard?`CPU가 버림패에서 가져오기: ${cardText(c)}.`:'CPU가 개인 덱에서 1장 뽑았습니다.');if(fromDiscard)onDiscardDraw('enemy',c)}
const urgent=state.switchTarget==='enemy'&&state.switchPower>0;if(urgent&&!bestExtension('enemy')&&maintenanceLimit('enemy')>0){const swaps=chooseAIMaintenanceCards().slice(0,maintenanceLimit('enemy'));if(swaps.length)performMaintenance('enemy',swaps)}else if(!hasAnyLegalAction('enemy')&&maintenanceLimit('enemy')>0){const swaps=chooseAIMaintenanceCards().slice(0,maintenanceLimit('enemy'));if(swaps.length)performMaintenance('enemy',swaps)}
const actionCap=state.sessionMode==='practice'?2:4;let actions=0,rummied=false;while(actions++<actionCap&&!state.gameOver){const ex=bestExtension('enemy'),nm=!state.enemy.newMeldUsed&&state.enemy.melds.length<2?bestNewMeldForTurn('enemy'):null,rc=bestRecoverAI('enemy'),fr=bestFinishRunAI('enemy');const switchUrgent=state.switchTarget==='enemy'&&state.switchPower>0,coreNeed=state.enemy.hp+state.enemy.shield,acceptThreshold=Math.max(12,Math.floor(state.enemy.hp*.35+state.enemy.shield*.5)),acceptSmall=switchUrgent&&state.switchPower<coreNeed&&state.switchPower<=acceptThreshold;if(ex&&(!acceptSmall&&(switchUrgent||!nm||ex.score>=nm.score))&&(!rc||ex.score>=rc.score)){const r=attachCards('enemy',ex.cards,ex.side,ex.index);if(r==='rummy'){rummied=true;break}continue}if(rc&&(!nm||rc.score>nm.score)){executeRecoverAI('enemy',rc);continue}if(fr){finishRun('enemy',fr.index);continue}if(nm&&!state.enemy.newMeldUsed&&state.enemy.melds.length<2){const r=submitNewMeld('enemy',nm.cards);if(r==='rummy'){rummied=true;break}continue}break}
let lastDiscarded=null;while(!state.gameOver&&!rummied&&state.enemy.hand.length&&state.enemy.discardsRemaining>0){if(typeof canSkipBaseDiscard==='function'&&canSkipBaseDiscard('enemy')){if(typeof getCirculationStats==='function')getCirculationStats().lowSkips++;state.enemy.discardsRemaining=0;log(`상대 저손패 보호 · 손패 ${state.enemy.hand.length}장이라 기본 버리기 1회를 생략합니다.`,'important');break}let d=null;const lethalPending=state.switchTarget==='enemy'&&state.switchPower>=state.enemy.hp+state.enemy.shield;if(lethalPending&&!state.fuseUsed){d=state.enemy.hand.find(x=>x.tag==='safetyPin')||null}if(!d)d=chooseAIDiscard();if(!d)break;lastDiscarded=d;removeFromHand('enemy',[d]);if(d.tag==='topDeckChoice'&&Math.random()<.55){d.fromDiscard=false;d.contractActive=false;state.enemy.deck.push(d);log(`${d.name}: CPU가 덱 위로 예약 발송.`,'important')}else{const pawn=state.field?.tag==='pawnshop'&&d.fromDiscard;pushDiscard(d);state.lastEnemyDiscardRank=d.rank;log(`CPU 버리기: ${cardText(d)}`);armSafetyPin('enemy',d);if(pawn)addShield('enemy',3)}state.enemy.discardsRemaining=Math.max(0,(state.enemy.discardsRemaining||1)-1)}if(!state.gameOver&&!rummied&&state.enemy.hand.length===0){triggerRummy('enemy',lastDiscarded?[lastDiscarded]:[],{returned:false});rummied=true}settleContracts('enemy');turnEnd('enemy');if(state.gameOver){render();return}state.enemy.hand.forEach(c=>c.age++);state.turn='player';state.phase='draw';state.turnNo++;state.lastPlayerUsedDiscard=false;turnStart('player');prepareAcquisitionPhase('player');render()}"""
new_ai="""function continueAITurnAfterAcquisition(){if(state.gameOver||state.turn!=='enemy')return;const urgent=state.switchTarget==='enemy'&&state.switchPower>0;if(urgent&&!bestExtension('enemy')&&maintenanceLimit('enemy')>0){const swaps=chooseAIMaintenanceCards().slice(0,maintenanceLimit('enemy'));if(swaps.length)performMaintenance('enemy',swaps)}else if(!hasAnyLegalAction('enemy')&&maintenanceLimit('enemy')>0){const swaps=chooseAIMaintenanceCards().slice(0,maintenanceLimit('enemy'));if(swaps.length)performMaintenance('enemy',swaps)}
const actionCap=state.sessionMode==='practice'?2:4;let actions=0,rummied=false;while(actions++<actionCap&&!state.gameOver){const ex=bestExtension('enemy'),nm=!state.enemy.newMeldUsed&&state.enemy.melds.length<2?bestNewMeldForTurn('enemy'):null,rc=bestRecoverAI('enemy'),fr=bestFinishRunAI('enemy');const switchUrgent=state.switchTarget==='enemy'&&state.switchPower>0,coreNeed=state.enemy.hp+state.enemy.shield,acceptThreshold=Math.max(12,Math.floor(state.enemy.hp*.35+state.enemy.shield*.5)),acceptSmall=switchUrgent&&state.switchPower<coreNeed&&state.switchPower<=acceptThreshold;if(ex&&(!acceptSmall&&(switchUrgent||!nm||ex.score>=nm.score))&&(!rc||ex.score>=rc.score)){const r=attachCards('enemy',ex.cards,ex.side,ex.index);if(r==='rummy'){rummied=true;break}continue}if(rc&&(!nm||rc.score>nm.score)){executeRecoverAI('enemy',rc);continue}if(fr){finishRun('enemy',fr.index);continue}if(nm&&!state.enemy.newMeldUsed&&state.enemy.melds.length<2){const r=submitNewMeld('enemy',nm.cards);if(r==='rummy'){rummied=true;break}continue}break}
let lastDiscarded=null;while(!state.gameOver&&!rummied&&state.enemy.hand.length&&state.enemy.discardsRemaining>0){if(typeof canSkipBaseDiscard==='function'&&canSkipBaseDiscard('enemy')){if(typeof getCirculationStats==='function')getCirculationStats().lowSkips++;state.enemy.discardsRemaining=0;log(`상대 저손패 보호 · 손패 ${state.enemy.hand.length}장이라 기본 버리기 1회를 생략합니다.`,'important');break}let d=null;const lethalPending=state.switchTarget==='enemy'&&state.switchPower>=state.enemy.hp+state.enemy.shield;if(lethalPending&&!state.fuseUsed){d=state.enemy.hand.find(x=>x.tag==='safetyPin')||null}if(!d)d=chooseAIDiscard();if(!d)break;lastDiscarded=d;removeFromHand('enemy',[d]);if(d.tag==='topDeckChoice'&&Math.random()<.55){d.fromDiscard=false;d.contractActive=false;state.enemy.deck.push(d);log(`${d.name}: CPU가 덱 위로 예약 발송.`,'important')}else{const pawn=state.field?.tag==='pawnshop'&&d.fromDiscard;pushDiscard(d);state.lastEnemyDiscardRank=d.rank;log(`CPU 버리기: ${cardText(d)}`);armSafetyPin('enemy',d);if(pawn)addShield('enemy',3)}state.enemy.discardsRemaining=Math.max(0,(state.enemy.discardsRemaining||1)-1)}if(!state.gameOver&&!rummied&&state.enemy.hand.length===0){triggerRummy('enemy',lastDiscarded?[lastDiscarded]:[],{returned:false});rummied=true}settleContracts('enemy');turnEnd('enemy');if(state.gameOver){render();return}state.enemy.hand.forEach(c=>c.age++);state.turn='player';state.phase='draw';state.turnNo++;state.lastPlayerUsedDiscard=false;turnStart('player');prepareAcquisitionPhase('player');render()}
function aiTurn(){if(state.gameOver)return;turnStart('enemy');state.turn='enemy';state.phase='wait';state.lastEnemyUsedDiscard=false;const acquisition=prepareAcquisitionPhase('enemy');if(state.gameOver){render();return}let fromDiscard=false,top=state.discard.at(-1);if(!state.enemy.blockOpponentDiscardNext&&top&&discardHelpsAI(top))fromDiscard=true;let c=null;if(acquisition==='draw'){if(fromDiscard&&state.field?.tag==='blackMarket'&&state.discard.length>=2){const a=state.discard.at(-1),b=state.discard.at(-2);if(aiCardChoiceScore(b)>aiCardChoiceScore(a)){const rm=state.discard.pop();sideObj(rm.owner).spent.push(rm);c=acquireDiscardCard('enemy',0)}else c=drawOne('enemy',true)}else c=fromDiscard?drawOne('enemy',true):drawOne('enemy',false)}if(state.enemy.blockOpponentDiscardNext)state.enemy.blockOpponentDiscardNext=false;state.lastEnemyUsedDiscard=fromDiscard;if(c){log(fromDiscard?`CPU가 버림패에서 가져오기: ${cardText(c)}.`:'CPU가 개인 덱에서 1장 뽑았습니다.');if(fromDiscard){const battleId=state.battleId,turnToken=state.turnToken,paused=onDiscardDraw('enemy',c,{onAsyncResolved:()=>{if(isLiveCombatSession()&&state.battleId===battleId&&state.turnToken===turnToken&&state.turn==='enemy'&&!state.gameOver)continueAITurnAfterAcquisition()}});if(paused){render();return}}}continueAITurnAfterAcquisition()}"""
replace_once(old_ai,new_ai,'split AI turn around off-turn choice')

p.write_text(s,encoding='utf-8')

road=Path('ROADMAP.md')
r=road.read_text(encoding='utf-8')
old='- [ ] Add an off-turn choice continuation so Bait can let the human owner choose the hand card to bottom without the CPU turn racing ahead\n'
new='- [x] Add an off-turn choice continuation: when CPU takes a human-owned Bait, the owner draws first, chooses the exact hand card to bottom, and CPU play resumes only after that choice resolves\n'
if old not in r: raise SystemExit('missing roadmap off-turn item')
r=r.replace(old,new,1)
road.write_text(r,encoding='utf-8')

test=Path('tests/named-offturn-choice.mjs')
test.write_text(r'''import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
function ok(v,m){if(!v)throw new Error(m);console.log(`PASS: ${m}`)}
function source(name){const marker=`function ${name}(`,start=script.indexOf(marker);if(start<0)throw new Error(`missing ${name}`);let brace=-1,paren=0;for(let i=start+marker.length-1;i<script.length;i++){const ch=script[i];if(ch==='(')paren++;else if(ch===')')paren--;else if(ch==='{'&&paren===0){brace=i;break}}if(brace<0)throw new Error(`missing body ${name}`);let d=0;for(let i=brace;i<script.length;i++){if(script[i]==='{')d++;else if(script[i]==='}'&&--d===0)return script.slice(start,i+1)}throw new Error(`unterminated ${name}`)}
const onDraw=source('onDiscardDraw'),choice=source('requestHandBottomChoice'),bottom=source('bottomSpecificHandCard'),ai=source('aiTurn'),resume=source('continueAITurnAfterAcquisition');
ok(onDraw.includes("c.tag==='bait'&&c.originOwner!==w")&&onDraw.indexOf('drawOne(owner,false)')<onDraw.indexOf('requestHandBottomChoice(owner'),'Bait draws for its original owner before asking which hand card to bottom');
ok(choice.includes("w==='player'")&&choice.includes('requestEffectChoice')&&choice.includes('candidates.length>1'),'human owner receives shared modal choice when multiple Bait bottom candidates exist');
ok(!choice.includes('allowSkip:true'),'Bait hand-bottom choice is mandatory rather than skippable');
ok(bottom.includes('side.deck.unshift(chosen)')&&bottom.includes('chosen.contractActive=false')&&bottom.includes('chosen.age=0'),'chosen Bait cycle card is normalized and sent to deck bottom');
ok(ai.includes("paused=onDiscardDraw('enemy',c")&&ai.includes('if(paused){render();return}'),'AI acquisition returns immediately while an off-turn Bait choice is pending');
ok(ai.includes('battleId=state.battleId')&&ai.includes('turnToken=state.turnToken')&&ai.includes("state.turn==='enemy'")&&ai.includes('continueAITurnAfterAcquisition()'),'AI continuation is guarded against stale battle/turn callbacks');
ok(resume.includes('performMaintenance')&&resume.includes("bestExtension('enemy')")&&resume.includes("turnEnd('enemy')"),'post-acquisition AI continuation owns maintenance, actions, discard and turn end');
ok(!resume.includes("turnStart('enemy')"),'resuming after Bait does not restart the CPU turn');
ok(fs.readFileSync(new URL('../ROADMAP.md',import.meta.url),'utf8').includes('CPU play resumes only after that choice resolves'),'roadmap records completed off-turn Bait continuation');
console.log('M8 off-turn choice regression passed.');
''',encoding='utf-8')
