from pathlib import Path
p=Path(__file__).resolve().parents[2]/'tests'/'m11a-roguelike-run-init.mjs'
s=p.read_text(encoding='utf-8')
old="""  vm.runInContext(\"const ROGUELIKE_RUN_DRAFT_KEY='rummyDuelRoguelikeRunDraftV1'; const ROGUELIKE_COMMON_START_ZONE='common-start'; const ROGUELIKE_STARTER_IDS=Object.freeze(['wanderer','collector','salvager','jester','pure']); const CORE_IDS=['S3','S4','S5','S6','S7','S8','S9','H2','H3','H4','H7','H8','H9','D2','D3','D4','D5','D6','D7','D8','C3','C4','C5','C6','C7','C8','C9','S10','H10','D10','C10']; const ROGUELIKE_STARTER_REGULAR_SLOTS=Object.freeze(CORE_IDS.slice(0,29)); const ROGUELIKE_STARTER_DECK_SIZE=30; const ROGUELIKE_STARTER_NAMED_REGULAR_COUNT=6;\",ctx);"""
new="""  vm.runInContext(\"const ROGUELIKE_RUN_DRAFT_KEY='rummyDuelRoguelikeRunDraftV1'; const ROGUELIKE_COMMON_START_ZONE='common-start'; const ROGUELIKE_STARTER_IDS=Object.freeze(['wanderer','collector','salvager','jester','pure']); const CORE_IDS=['S3','S4','S5','S6','S7','S8','S9','H2','H3','H4','H7','H8','H9','D2','D3','D4','D5','D6','D7','D8','C3','C4','C5','C6','C7','C8','C9','S10','H10','D10','C10']; const ROGUELIKE_STARTER_REGULAR_SLOTS=Object.freeze(CORE_IDS.slice(0,29)); const ROGUELIKE_STARTER_DECK_SIZE=30; const ROGUELIKE_STARTER_NAMED_REGULAR_COUNT=6; const ROGUELIKE_STARTER_LOADOUTS=Object.freeze({wanderer:Object.freeze({regular:Object.freeze({H2:'H2',C5:'C5',S10:'S10',D2:'D2',C6:'C6',H10:'H10'}),joker:'J1'}),collector:Object.freeze({regular:Object.freeze({S9:'S9',H7:'H7',H8:'H8',H9:'H9',D7:'D7B',D8:'D8'}),joker:'J3'}),salvager:Object.freeze({regular:Object.freeze({S3:'S3',S4:'S4',D3:'D3',D7:'D7',C7:'C7',H3:'H3'}),joker:'J4'}),jester:Object.freeze({regular:Object.freeze({C8:'C8',D6:'D6',D5:'D5',D4:'D4',C4:'C4',C3:'C3'}),joker:'J5'}),pure:Object.freeze({regular:Object.freeze({}),joker:null})});\",ctx);"""
if old not in s: raise SystemExit('missing run-init constant anchor')
s=s.replace(old,new,1)
old2="install(ctx,'normalizeRoguelikeStarterId','roguelikeStarterUnlocked','roguelikeStarterProfile','roguelikeStarterDeckPlan','createRoguelikeRunDraft'"
new2="install(ctx,'normalizeRoguelikeStarterId','roguelikeStarterUnlocked','roguelikeStarterProfile','roguelikeStarterLoadout','roguelikeStarterDeckPlan','createRoguelikeRunDraft'"
if old2 not in s: raise SystemExit('missing run-init helper install anchor')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
