from pathlib import Path

root=Path('.')
index=root/'index.html'
roadmap=root/'ROADMAP.md'
text=index.read_text(encoding='utf-8')
road=roadmap.read_text(encoding='utf-8')

def rep(src,old,new,label):
    if old not in src:
        raise SystemExit(f'missing anchor: {label}')
    return src.replace(old,new,1)

# Start-screen advanced tutorial entry.
old='<div class="startAux"><button id="startProgressBtn" class="pixelBtn" type="button">캐릭터·해금</button><button id="startRulesBtn" class="pixelBtn" type="button">규칙·용어</button><button id="practiceStartBtn" class="pixelBtn practiceStartBtn" type="button">자유 연습전 · 진행도 영향 없음</button></div>'
new='<div class="startAux"><button id="startProgressBtn" class="pixelBtn" type="button">캐릭터·해금</button><button id="startRulesBtn" class="pixelBtn" type="button">규칙·용어</button><button id="advancedTutorialBtn" class="pixelBtn" type="button" disabled aria-disabled="true">고급 튜토리얼 · 기본 완료 후</button><button id="practiceStartBtn" class="pixelBtn practiceStartBtn" type="button">자유 연습전 · 진행도 영향 없음</button></div>'
text=rep(text,old,new,'advanced tutorial start button')

# Split basic and advanced tutorial segments.
old=" {id:'rummy',title:'러미',goal:'마지막 손패를 사용해 손패를 0장으로 만들고 러미 6장 리필을 직접 발생시킵니다.',hint:'강조된 K♠를 선택해 버리세요. 손패가 0장이 되는 순간 실제 러미 처리로 새 손패 6장을 받습니다.',implemented:true,scenario:'rummy',allow:['select','discard','clear'],selectRoles:['rummyLast'],discardRole:'rummyLast',expectReload:6,completeOn:'rummy'}\n]);"
new=""" {id:'rummy',title:'러미',goal:'마지막 손패를 사용해 손패를 0장으로 만들고 러미 6장 리필을 직접 발생시킵니다.',hint:'강조된 K♠를 선택해 버리세요. 손패가 0장이 되는 순간 실제 러미 처리로 새 손패 6장을 받습니다.',implemented:true,scenario:'rummy',allow:['select','discard','clear'],selectRoles:['rummyLast'],discardRole:'rummyLast',expectReload:6,completeOn:'rummy',stopAfter:true},
 {id:'recover',title:'회수',goal:'공개 조합에서 내 카드를 손패로 되돌리되, 카드를 빼고도 원래 조합이 유효해야 합니다.',hint:'내 4♣-5♣-6♣-7♣ 런에서 강조된 7♣를 선택한 뒤 회수하세요. RUN 회수는 체인이 1 감소하고, 회수한 카드는 같은 턴 버스트/체인 반환에 바로 재사용할 수 없습니다.',implemented:true,scenario:'recover',allow:['boardSelect','recover','clear'],boardRoles:['recoverCard'],boardSide:'player',expectRecoverRole:'recoverCard',completeOn:'recover'},
 {id:'maintenance',title:'정비',goal:'손패 1장을 덱 아래로 보내고 같은 수만큼 교체해 패를 정리합니다.',hint:'강조된 Q♣를 선택하고 정비하세요. Q♣는 덱 아래로 가고, 고정된 다음 카드 A♠를 받습니다.',implemented:true,scenario:'maintenance',allow:['select','maintenance','clear'],selectRoles:['maintenanceSwap'],expectMaintenanceDraw:'maintenanceDraw',completeOn:'maintenance'},
 {id:'status',title:'공식 상태',goal:'취약·봉인·고정·보호·재생은 정해진 시점에 작동하거나 소모되는 공통 상태입니다. 여기서는 취약을 실제 폭발로 확인합니다.',hint:'현재 취약 1 때문에 다음 폭발 피해가 +25%입니다. 강조된 5♠를 버리면 누적 8이 실제 피해 10이 되고 취약이 소모됩니다.',implemented:true,scenario:'status',allow:['select','discard','clear'],selectRoles:['statusEnd'],discardRole:'statusEnd',expectPower:8,expectDamage:10,expectVulnerableConsumed:true,expectReset:true,completeOn:'detonate',stopAfter:true}
]);"""
text=rep(text,old,new,'advanced tutorial steps')

# Start-screen state + advanced starter.
old="function renderStartScreen(){const el=document.getElementById('startMeta');if(!el)return;const id=charUnlocked(progress.selectedChar)?progress.selectedChar:'wanderer',ch=CHARACTERS[id]||CHARACTERS.wanderer;el.textContent=`${ch.name} Lv.${charLevel(progress,id)} · 전체 ${progress.totalClears}클리어`;const prompt=document.getElementById('firstRunPrompt'),note=document.getElementById('startResumeNote'),tutorialBtn=document.getElementById('tutorialStartBtn'),tutorialState=tutorialBtn?.querySelector('.menuState'),tutorialSmall=tutorialBtn?.querySelector('small');if(prompt)prompt.hidden=!!progress.tutorialPromptSeen;if(note)note.textContent=progress.tutorialCompleted?'기본 튜토리얼 완료 · 자유 연습전에서 반복하거나 언제든 다시 볼 수 있습니다.':progress.tutorialPromptSeen?'기본 조작부터 폭발·러미까지 고정 패 튜토리얼을 시작할 수 있습니다.':'처음이라면 짧은 튜토리얼을 권장합니다. 강제 진행은 없습니다.';if(tutorialState)tutorialState.textContent=progress.tutorialCompleted?'다시 보기':'시작';if(tutorialSmall)tutorialSmall.textContent=progress.tutorialCompleted?'기본 튜토리얼을 처음부터 다시 플레이합니다.':'기본 조작부터 폭발·러미까지 고정 패로 직접 익힙니다.'}"
new="function renderStartScreen(){const el=document.getElementById('startMeta');if(!el)return;const id=charUnlocked(progress.selectedChar)?progress.selectedChar:'wanderer',ch=CHARACTERS[id]||CHARACTERS.wanderer;el.textContent=`${ch.name} Lv.${charLevel(progress,id)} · 전체 ${progress.totalClears}클리어`;const prompt=document.getElementById('firstRunPrompt'),note=document.getElementById('startResumeNote'),tutorialBtn=document.getElementById('tutorialStartBtn'),tutorialState=tutorialBtn?.querySelector('.menuState'),tutorialSmall=tutorialBtn?.querySelector('small'),advanced=document.getElementById('advancedTutorialBtn');if(prompt)prompt.hidden=!!progress.tutorialPromptSeen;if(note)note.textContent=progress.tutorialCompleted?'기본 튜토리얼 완료 · 고급 튜토리얼이나 자유 연습전으로 이어갈 수 있습니다.':progress.tutorialPromptSeen?'기본 조작부터 폭발·러미까지 고정 패 튜토리얼을 시작할 수 있습니다.':'처음이라면 짧은 튜토리얼을 권장합니다. 강제 진행은 없습니다.';if(tutorialState)tutorialState.textContent=progress.tutorialCompleted?'다시 보기':'시작';if(tutorialSmall)tutorialSmall.textContent=progress.tutorialCompleted?'기본 튜토리얼을 처음부터 다시 플레이합니다.':'기본 조작부터 폭발·러미까지 고정 패로 직접 익힙니다.';if(advanced){advanced.disabled=!progress.tutorialCompleted;advanced.setAttribute('aria-disabled',String(!progress.tutorialCompleted));advanced.textContent=progress.tutorialCompleted?'고급 튜토리얼 · 회수/정비/상태':'고급 튜토리얼 · 기본 완료 후'}}"
text=rep(text,old,new,'advanced start-screen state')

old="function startTutorial(stepId='intro'){progress.tutorialPromptSeen=true;saveProgress();hideStartScreen();document.getElementById('overlay')?.classList.remove('show');newGame('tutorial');setTutorialStep(stepId);renderStartScreen()}"
new="function startTutorial(stepId='intro'){progress.tutorialPromptSeen=true;saveProgress();hideStartScreen();document.getElementById('overlay')?.classList.remove('show');newGame('tutorial');setTutorialStep(stepId);renderStartScreen()}\nfunction startAdvancedTutorial(){if(!progress.tutorialCompleted){log('고급 튜토리얼은 기본 튜토리얼 완료 후 열립니다.','hit');renderStartScreen();return false}startTutorial('recover');return true}"
text=rep(text,old,new,'advanced tutorial starter')

# Tutorial action gates.
old="function tutorialAllows(action,context={}){if(state.sessionMode!=='tutorial')return true;const step=currentTutorialStep();if(!step||!step.implemented||!Array.isArray(step.allow)||!step.allow.includes(action))return false;if(action==='select'&&step.selectRoles?.length&&!step.selectRoles.includes(context.card?.tutorialRole))return false;if(action==='discard'&&step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;if(action==='meld'&&step.expectMeld&&context.type!==step.expectMeld)return false;if(action==='attach'){if(step.attachSide&&context.targetSide!==step.attachSide)return false;if(step.expectAttach&&context.type!==step.expectAttach)return false}return true}"
new="function tutorialAllows(action,context={}){if(state.sessionMode!=='tutorial')return true;const step=currentTutorialStep();if(!step||!step.implemented||!Array.isArray(step.allow)||!step.allow.includes(action))return false;if(action==='select'&&step.selectRoles?.length&&!step.selectRoles.includes(context.card?.tutorialRole))return false;if(action==='boardSelect'){if(step.boardRoles?.length&&!step.boardRoles.includes(context.card?.tutorialRole))return false;if(step.boardSide&&context.targetSide!==step.boardSide)return false}if(action==='discard'&&step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;if(action==='meld'&&step.expectMeld&&context.type!==step.expectMeld)return false;if(action==='attach'){if(step.attachSide&&context.targetSide!==step.attachSide)return false;if(step.expectAttach&&context.type!==step.expectAttach)return false}if(action==='recover'){if(step.boardSide&&context.plan?.side!==step.boardSide)return false;if(step.expectRecoverRole&&context.plan?.card?.tutorialRole!==step.expectRecoverRole)return false}return true}"
text=rep(text,old,new,'advanced tutorial action gates')

# Deterministic scenarios.
old="else if(step.scenario==='rummy'){p.hand=[makeTutorialCard('S','K','rummyLast')];p.deck=[makeTutorialCard('C','2','rummyReload'),makeTutorialCard('D','4','rummyReload'),makeTutorialCard('H','6','rummyReload'),makeTutorialCard('S','8','rummyReload'),makeTutorialCard('C','10','rummyReload'),makeTutorialCard('D','Q','rummyReload')];state.phase='action';log('러미 실습 · 마지막 K♠를 버려 손패를 0장으로 만들고 새 손패 6장을 받으세요.','important')}return true}"
new="else if(step.scenario==='rummy'){p.hand=[makeTutorialCard('S','K','rummyLast')];p.deck=[makeTutorialCard('C','2','rummyReload'),makeTutorialCard('D','4','rummyReload'),makeTutorialCard('H','6','rummyReload'),makeTutorialCard('S','8','rummyReload'),makeTutorialCard('C','10','rummyReload'),makeTutorialCard('D','Q','rummyReload')];state.phase='action';log('러미 실습 · 마지막 K♠를 버려 손패를 0장으로 만들고 새 손패 6장을 받으세요.','important')}else if(step.scenario==='recover'){p.hand=[makeTutorialCard('D','Q','hold')];p.melds=[makeTutorialMeld('player','RUN',[makeTutorialCard('C','4','board','player'),makeTutorialCard('C','5','board','player'),makeTutorialCard('C','6','board','player'),makeTutorialCard('C','7','recoverCard','player')],1)];state.phase='action';log('고급 회수 실습 · 내 런의 7♣를 회수해 4♣-5♣-6♣를 유지하세요. RUN 회수는 체인 -1입니다.','important')}else if(step.scenario==='maintenance'){p.hand=[makeTutorialCard('C','Q','maintenanceSwap'),makeTutorialCard('S','3','hold'),makeTutorialCard('H','3','hold'),makeTutorialCard('D','3','hold')];p.deck=[makeTutorialCard('S','A','maintenanceDraw')];state.phase='action';log('고급 정비 실습 · Q♣를 덱 아래로 보내고 A♠로 교체하세요.','important')}else if(step.scenario==='status'){p.hand=[makeTutorialCard('S','5','statusEnd'),makeTutorialCard('D','9','hold')];applyOfficialStatus('player',p,'vulnerable',1,{silent:true});state.switchTarget='player';state.switchPower=8;state.phase='action';log('공식 상태 실습 · 취약 1은 다음 폭발 피해를 25% 늘리고 소모됩니다. 5♠를 버려 8 → 10 피해를 확인하세요.','important')}return true}"
text=rep(text,old,new,'advanced deterministic scenarios')

# Segment-aware tutorial badge and segment-end controls.
old="function currentTutorialStep(){return TUTORIAL_STEPS.find(x=>x.id===state.tutorialStep)||null}\nfunction tutorialStepIndex(id=state.tutorialStep){return TUTORIAL_STEPS.findIndex(x=>x.id===id)}"
new="function currentTutorialStep(){return TUTORIAL_STEPS.find(x=>x.id===state.tutorialStep)||null}\nfunction tutorialStepIndex(id=state.tutorialStep){return TUTORIAL_STEPS.findIndex(x=>x.id===id)}\nfunction tutorialSegmentInfo(id=state.tutorialStep){const idx=tutorialStepIndex(id),advanced=TUTORIAL_STEPS.findIndex(x=>x.id==='recover'),basicEnd=TUTORIAL_STEPS.findIndex(x=>x.id==='rummy');if(idx>=advanced&&advanced>=0)return{label:'고급 튜토리얼',position:idx-advanced+1,total:TUTORIAL_STEPS.length-advanced};return{label:'튜토리얼',position:Math.max(1,idx+1),total:basicEnd>=0?basicEnd+1:TUTORIAL_STEPS.length}}"
text=rep(text,old,new,'segment info')

old="function renderTutorialCoach(){const coach=document.getElementById('tutorialCoach'),step=currentTutorialStep();if(!coach)return;if(state.sessionMode!=='tutorial'||!step){coach.hidden=true;return}coach.hidden=false;document.getElementById('tutorialStepBadge').textContent=`튜토리얼 ${Math.max(1,tutorialStepIndex()+1)} / ${TUTORIAL_STEPS.length}`;document.getElementById('tutorialCoachTitle').textContent=state.tutorialSegmentDone?`${step.title} · 성공`:step.title;document.getElementById('tutorialCoachGoal').textContent=state.tutorialSuccessText||step.goal;const hint=document.getElementById('tutorialCoachHint'),exit=document.getElementById('tutorialExitBtn');if(state.tutorialExitArmed){hint.textContent='현재 단계는 처음 상태로 되돌아갑니다. 완료한 튜토리얼 기록은 유지됩니다. 종료 버튼을 한 번 더 누르면 메인으로 돌아갑니다.';hint.hidden=false}else{hint.textContent=state.tutorialSegmentDone?(step.id==='rummy'?'기본 튜토리얼 완료! 자유 연습전으로 이어가거나 메인으로 돌아갈 수 있습니다.':'다음 실습은 잠시 후 자동으로 시작됩니다.'):step.hint||'';hint.hidden=state.tutorialSegmentDone?false:!state.tutorialHintOpen}if(exit){exit.textContent=state.tutorialExitArmed?'한 번 더 눌러 종료':'튜토리얼 종료';exit.classList.toggle('armed',!!state.tutorialExitArmed)}const next=document.getElementById('tutorialNextBtn'),practice=document.getElementById('tutorialPracticeBtn');if(practice)practice.hidden=!(state.tutorialSegmentDone&&step.id==='rummy');if(state.tutorialSegmentDone){next.hidden=false;next.disabled=step.id!=='rummy';next.textContent=step.id==='rummy'?'튜토리얼 완료 · 메인으로':'자동 진행 중'}else{next.hidden=!step.manualNext;next.disabled=false;next.textContent=step.id==='intro'?'화면 보기':step.id==='board'?'실습 시작':'다음'}}"
new="function renderTutorialCoach(){const coach=document.getElementById('tutorialCoach'),step=currentTutorialStep();if(!coach)return;if(state.sessionMode!=='tutorial'||!step){coach.hidden=true;return}coach.hidden=false;const seg=tutorialSegmentInfo();document.getElementById('tutorialStepBadge').textContent=`${seg.label} ${seg.position} / ${seg.total}`;document.getElementById('tutorialCoachTitle').textContent=state.tutorialSegmentDone?`${step.title} · 성공`:step.title;document.getElementById('tutorialCoachGoal').textContent=state.tutorialSuccessText||step.goal;const hint=document.getElementById('tutorialCoachHint'),exit=document.getElementById('tutorialExitBtn'),segmentEnd=!!step.stopAfter||!TUTORIAL_STEPS[tutorialStepIndex()+1]?.implemented;if(state.tutorialExitArmed){hint.textContent='현재 단계는 처음 상태로 되돌아갑니다. 완료한 튜토리얼 기록은 유지됩니다. 종료 버튼을 한 번 더 누르면 메인으로 돌아갑니다.';hint.hidden=false}else{hint.textContent=state.tutorialSegmentDone?(step.id==='rummy'?'기본 튜토리얼 완료! 고급 튜토리얼·자유 연습전으로 이어가거나 메인으로 돌아갈 수 있습니다.':step.id==='status'?'고급 튜토리얼 1차 완료! 회수·정비·공식 상태의 핵심을 확인했습니다.':'다음 실습은 잠시 후 자동으로 시작됩니다.'):step.hint||'';hint.hidden=state.tutorialSegmentDone?false:!state.tutorialHintOpen}if(exit){exit.textContent=state.tutorialExitArmed?'한 번 더 눌러 종료':'튜토리얼 종료';exit.classList.toggle('armed',!!state.tutorialExitArmed)}const next=document.getElementById('tutorialNextBtn'),practice=document.getElementById('tutorialPracticeBtn');if(practice)practice.hidden=!(state.tutorialSegmentDone&&segmentEnd);if(state.tutorialSegmentDone){next.hidden=false;next.disabled=!segmentEnd;next.textContent=segmentEnd?(step.id==='rummy'?'기본 튜토리얼 완료 · 메인으로':'고급 튜토리얼 완료 · 메인으로'):'자동 진행 중'}else{next.hidden=!step.manualNext;next.disabled=false;next.textContent=step.id==='intro'?'화면 보기':step.id==='board'?'실습 시작':'다음'}}"
text=rep(text,old,new,'segment-aware coach')

# Progress checks + stopAfter boundary.
old="if(step.expectReload&&context.afterHand!==step.expectReload)return false;if(step.expectPower!=null&&context.beforePower!==step.expectPower)return false;if(step.expectShieldAbsorb!=null&&context.beforeShield-context.afterShield!==step.expectShieldAbsorb)return false;if(step.expectCoreBreak&&context.afterCores!==context.beforeCores-1)return false;if(step.expectNextCoreHp&&context.afterHp!==step.expectNextCoreHp)return false;if(step.expectReset&&!(context.afterPower===0&&context.afterTarget==='neutral'))return false;const next=TUTORIAL_STEPS[tutorialStepIndex()+1];"
new="if(step.expectReload&&context.afterHand!==step.expectReload)return false;if(step.expectRecoverRole&&context.card?.tutorialRole!==step.expectRecoverRole)return false;if(step.expectMaintenanceDraw&&context.got?.[0]?.tutorialRole!==step.expectMaintenanceDraw)return false;if(step.expectPower!=null&&context.beforePower!==step.expectPower)return false;if(step.expectDamage!=null&&context.dealt!==step.expectDamage)return false;if(step.expectVulnerableConsumed&&!(context.beforeVulnerable>0&&context.afterVulnerable===0))return false;if(step.expectShieldAbsorb!=null&&context.beforeShield-context.afterShield!==step.expectShieldAbsorb)return false;if(step.expectCoreBreak&&context.afterCores!==context.beforeCores-1)return false;if(step.expectNextCoreHp&&context.afterHp!==step.expectNextCoreHp)return false;if(step.expectReset&&!(context.afterPower===0&&context.afterTarget==='neutral'))return false;const next=TUTORIAL_STEPS[tutorialStepIndex()+1];"
text=rep(text,old,new,'advanced progress checks')

old="state.tutorialSuccessText=event==='discard'?'좋아요. 카드를 뽑고 선택해 버리는 기본 흐름을 익혔습니다.':event==='detonate'?`폭발 확인! 보호막 ${context.beforeShield-context.afterShield} 흡수 → 현재 코어 ${context.dealt} 피해·파괴. 다음 코어 ${context.afterHp}/${CORE_HP}, 초과 피해는 관통하지 않고 스위치는 중립으로 초기화되었습니다.`:event==='rummy'?`러미 성공! 손패 ${context.beforeHand}장에서 새 손패 ${context.afterHand}장으로 즉시 리필되었습니다. 기본 튜토리얼을 완료했습니다.`:event==='attach'?step.id==='attachEnemy'?'상대 공개 조합도 내 공격 경로로 사용할 수 있습니다.':step.id==='switch'?`버스트 성공! 누적 위력 ${context.beforePower} → ${context.afterPower}, 스위치가 상대에게 넘어갔습니다.`:`붙이기 성공! 실제 체인 처리로 누적 위력 ${context.afterPower}이 만들어졌습니다.`:`${step.title} 완성! 실제 조합 판정 엔진이 성공을 확인했습니다.`;"
new="state.tutorialSuccessText=event==='discard'?'좋아요. 카드를 뽑고 선택해 버리는 기본 흐름을 익혔습니다.':event==='recover'?`회수 성공! ${cardText(context.card)}가 손패로 돌아왔고 RUN 체인이 ${context.beforeChain} → ${context.afterChain}로 1 감소했습니다.`:event==='maintenance'?`정비 성공! ${cardText(context.sent?.[0])}를 덱 아래로 보내고 ${cardText(context.got?.[0])}로 교체했습니다.`:event==='detonate'&&step.id==='status'?`취약 확인! 누적 ${context.beforePower}이 실제 피해 ${context.dealt}로 증가했고 취약이 소모된 뒤 스위치는 중립으로 돌아갔습니다.`:event==='detonate'?`폭발 확인! 보호막 ${context.beforeShield-context.afterShield} 흡수 → 현재 코어 ${context.dealt} 피해·파괴. 다음 코어 ${context.afterHp}/${CORE_HP}, 초과 피해는 관통하지 않고 스위치는 중립으로 초기화되었습니다.`:event==='rummy'?`러미 성공! 손패 ${context.beforeHand}장에서 새 손패 ${context.afterHand}장으로 즉시 리필되었습니다. 기본 튜토리얼을 완료했습니다.`:event==='attach'?step.id==='attachEnemy'?'상대 공개 조합도 내 공격 경로로 사용할 수 있습니다.':step.id==='switch'?`버스트 성공! 누적 위력 ${context.beforePower} → ${context.afterPower}, 스위치가 상대에게 넘어갔습니다.`:`붙이기 성공! 실제 체인 처리로 누적 위력 ${context.afterPower}이 만들어졌습니다.`:`${step.title} 완성! 실제 조합 판정 엔진이 성공을 확인했습니다.`;"
text=rep(text,old,new,'advanced success text')

old="if(next?.implemented){render();renderTutorialCoach();if(typeof pulseTutorialSuccess==='function')pulseTutorialSuccess();const battleId=state.battleId,stepId=step.id,stepToken=state.tutorialStepToken;setTimeout(()=>{if(state.sessionMode==='tutorial'&&state.battleId===battleId&&state.tutorialStep===stepId&&state.tutorialStepToken===stepToken)setTutorialStep(next.id)},850);return true}"
new="if(next?.implemented&&!step.stopAfter){render();renderTutorialCoach();if(typeof pulseTutorialSuccess==='function')pulseTutorialSuccess();const battleId=state.battleId,stepId=step.id,stepToken=state.tutorialStepToken;setTimeout(()=>{if(state.sessionMode==='tutorial'&&state.battleId===battleId&&state.tutorialStep===stepId&&state.tutorialStepToken===stepToken)setTutorialStep(next.id)},850);return true}"
text=rep(text,old,new,'stopAfter boundary')

# Highlights for advanced actions/status.
old="if(step.allow?.includes('attach')){const side=step.attachSide||'player',m=meldsOf(side)[0],type=m?.type;const entry=document.querySelector(`.meldEntry[data-side=\"${side}\"][data-index=\"0\"]`);if(entry)entry.classList.add('tutorialTarget');if(cs.length&&tutorialAllows('attach',{cards:cs,targetSide:side,targetIndex:0,type})&&canAttachTo(side,0,cs))document.querySelector(`.attachHereBtn[data-attach-side=\"${side}\"][data-attach-index=\"0\"]`)?.classList.add('tutorialTarget')}}"
new="if(step.allow?.includes('attach')){const side=step.attachSide||'player',m=meldsOf(side)[0],type=m?.type;const entry=document.querySelector(`.meldEntry[data-side=\"${side}\"][data-index=\"0\"]`);if(entry)entry.classList.add('tutorialTarget');if(cs.length&&tutorialAllows('attach',{cards:cs,targetSide:side,targetIndex:0,type})&&canAttachTo(side,0,cs))document.querySelector(`.attachHereBtn[data-attach-side=\"${side}\"][data-attach-index=\"0\"]`)?.classList.add('tutorialTarget')}if(step.allow?.includes('boardSelect'))document.querySelectorAll('.meldMiniCard').forEach(el=>{const side=el.dataset.side,mi=+el.dataset.index,ci=+el.dataset.card,c=meldsOf(side)[mi]?.cards[ci];if(c&&tutorialAllows('boardSelect',{card:c,targetSide:side}))el.classList.add('tutorialTarget')});const rp=recoverPlan();if(rp&&tutorialAllows('recover',{plan:rp}))document.getElementById('recoverBtn')?.classList.add('tutorialTarget');if(cs.length&&tutorialAllows('maintenance',{cards:cs}))document.getElementById('maintenanceBtn')?.classList.add('tutorialTarget');if(step.id==='status')document.querySelector('#pMeta .statusChip')?.classList.add('tutorialTarget')}"
text=rep(text,old,new,'advanced highlights')

old="function advanceTutorial(){const step=currentTutorialStep();if(!step)return;if(step.id==='intro'){setTutorialStep('board');return}if(step.id==='board'){setTutorialStep('basic');return}if(step.id==='rummy'&&state.tutorialSegmentDone){showStartScreen();return}}"
new="function advanceTutorial(){const step=currentTutorialStep();if(!step)return;if(step.stopAfter&&state.tutorialSegmentDone){showStartScreen();return}if(step.id==='intro'){setTutorialStep('board');return}if(step.id==='board'){setTutorialStep('basic');return}}"
text=rep(text,old,new,'segment end advance')

# Recovery engine hook.
old="function playerRecover(){const plan=recoverPlan();if(!plan){log('회수 불가 · 내 소유 카드 1장을 고르고, 빼도 조합이 유지되어야 합니다.','hit');return}const s=state.player,m=meldsOf(plan.side)[plan.mi],freeReason=recoveryFreeReason('player',plan.side,m,plan.card),[c]=m.cards.splice(plan.ci,1);s.hand.push(c);s.rummyRecoveryPending=false;if(!freeReason)s.recoveredThisTurn=true;else{if(freeReason==='tuner')s.flags.tuner=true;else if(freeReason==='roundabout')s.flags.roundabout=true;else if(freeReason==='rummy')s.freeRecoverAfterRummy=false;log(freeReason==='tuner'?'조율자 · 다른 종류 조합으로 옮길 수 있는 회수를 무료 처리하고 같은 턴 재사용을 허용합니다.':'무료 회수 · 기본 회수 횟수를 소모하지 않습니다.','good')}s.actedThisTurn=true;c.suppressEffectToken=state.turnToken;c.recoveredToken=state.turnToken;c.recoverReturnOverrideToken=freeReason==='tuner'?state.turnToken:null;c.age=0;if(m.type==='RUN')m.chain=Math.max(0,(m.chain||0)-1);markSetCompletion(m,plan.side);if(c.tag==='ambulance'){heal('player',2);if(plan.side==='enemy')addShield('player',2)}if(c.tag==='fuseRound'&&c.fuseArmed){addSwitchPower('player',16,c.name);c.fuseArmed=false}state.boardSelected.clear();state.target=null;log(`나 회수 · ${plan.side==='enemy'?'상대':'내'} 공개 조합의 ${cardText(c)} → 손패${m.type==='RUN'?' · 체인 -1':''}.`,'important');render()}"
new="function playerRecover(){const plan=recoverPlan();if(!plan){if(state.sessionMode==='tutorial')tutorialReject('recover');else log('회수 불가 · 내 소유 카드 1장을 고르고, 빼도 조합이 유지되어야 합니다.','hit');return}if(!tutorialAllows('recover',{plan})){tutorialReject('recover');return}const s=state.player,m=meldsOf(plan.side)[plan.mi],beforeChain=m.chain||0,freeReason=recoveryFreeReason('player',plan.side,m,plan.card),[c]=m.cards.splice(plan.ci,1);s.hand.push(c);s.rummyRecoveryPending=false;if(!freeReason)s.recoveredThisTurn=true;else{if(freeReason==='tuner')s.flags.tuner=true;else if(freeReason==='roundabout')s.flags.roundabout=true;else if(freeReason==='rummy')s.freeRecoverAfterRummy=false;log(freeReason==='tuner'?'조율자 · 다른 종류 조합으로 옮길 수 있는 회수를 무료 처리하고 같은 턴 재사용을 허용합니다.':'무료 회수 · 기본 회수 횟수를 소모하지 않습니다.','good')}s.actedThisTurn=true;c.suppressEffectToken=state.turnToken;c.recoveredToken=state.turnToken;c.recoverReturnOverrideToken=freeReason==='tuner'?state.turnToken:null;c.age=0;if(m.type==='RUN')m.chain=Math.max(0,(m.chain||0)-1);markSetCompletion(m,plan.side);if(c.tag==='ambulance'){heal('player',2);if(plan.side==='enemy')addShield('player',2)}if(c.tag==='fuseRound'&&c.fuseArmed){addSwitchPower('player',16,c.name);c.fuseArmed=false}state.boardSelected.clear();state.target=null;log(`나 회수 · ${plan.side==='enemy'?'상대':'내'} 공개 조합의 ${cardText(c)} → 손패${m.type==='RUN'?' · 체인 -1':''}.`,'important');if(tutorialCheckProgress('recover',{card:c,targetSide:plan.side,beforeChain,afterChain:m.chain||0}))return;render()}"
text=rep(text,old,new,'recovery tutorial hook')

# Maintenance engine hook.
old="function playerMaintenance(){if(state.turn!=='player'||state.phase!=='action')return;const limit=maintenanceLimit('player');if(!limit){log('정비 불가 · 이번 턴 정비를 이미 사용했거나 교체할 덱 카드가 없습니다.','hit');return}const cs=selectedCards();if(cs.length<1||cs.length>limit){log(limit===2?'정비할 손패 카드를 1~2장 선택하세요.':'평상시 정비는 손패 1장만 교체할 수 있습니다.','hit');return}const from=cs.map(c=>rectSnapshot(document.querySelector(`.cardBtn[data-uid=\"${c.uid}\"]`))),deckRect=rectSnapshot(document.getElementById('deckPile'));state.selected.clear();state.selectionOrder=[];const got=performMaintenance('player',cs);if(!got.length){log('정비할 덱 카드가 없습니다.','hit');render();return}render();from.forEach((r,i)=>{if(r&&deckRect)setTimeout(()=>flyCardBetween(r,deckRect,cs[i],false),i*70)});got.forEach((c,i)=>setTimeout(()=>animateDrawMove(false,c,deckRect),180+i*90))}"
new="function playerMaintenance(){if(state.turn!=='player'||state.phase!=='action')return;const limit=maintenanceLimit('player');if(!limit){log('정비 불가 · 이번 턴 정비를 이미 사용했거나 교체할 덱 카드가 없습니다.','hit');return}const cs=selectedCards();if(!tutorialAllows('maintenance',{cards:cs})){tutorialReject('maintenance');return}if(cs.length<1||cs.length>limit){log(limit===2?'정비할 손패 카드를 1~2장 선택하세요.':'평상시 정비는 손패 1장만 교체할 수 있습니다.','hit');return}const from=cs.map(c=>rectSnapshot(document.querySelector(`.cardBtn[data-uid=\"${c.uid}\"]`))),deckRect=rectSnapshot(document.getElementById('deckPile'));state.selected.clear();state.selectionOrder=[];const got=performMaintenance('player',cs);if(!got.length){log('정비할 덱 카드가 없습니다.','hit');render();return}render();from.forEach((r,i)=>{if(r&&deckRect)setTimeout(()=>flyCardBetween(r,deckRect,cs[i],false),i*70)});got.forEach((c,i)=>setTimeout(()=>animateDrawMove(false,c,deckRect),180+i*90));tutorialCheckProgress('maintenance',{sent:cs,got})}"
text=rep(text,old,new,'maintenance tutorial hook')

# DETONATE status lifecycle context.
old="const s=sideObj(w),tutorialBefore={power:state.switchPower,shield:s.shield,hp:s.hp,cores:s.cores};"
new="const s=sideObj(w),tutorialBefore={power:state.switchPower,shield:s.shield,hp:s.hp,cores:s.cores,vulnerable:officialStatusValue('player',s,'vulnerable')};"
text=rep(text,old,new,'detonate tutorial before status')
old="beforeCores:tutorialBefore.cores,afterCores:s.cores,dealt,afterPower:state.switchPower,afterTarget:state.switchTarget});"
new="beforeCores:tutorialBefore.cores,afterCores:s.cores,beforeVulnerable:tutorialBefore.vulnerable,afterVulnerable:officialStatusValue('player',s,'vulnerable'),dealt,afterPower:state.switchPower,afterTarget:state.switchTarget});"
text=rep(text,old,new,'detonate tutorial after status')

# Board selection gate for recovery lesson.
old="if(canRecoverCard('player',targetSide,mi,ci)){if(state.boardSelected.has(c.uid))state.boardSelected.clear();else{state.boardSelected.clear();state.boardSelected.add(c.uid)}renderMelds();updateButtons()}"
new="if(canRecoverCard('player',targetSide,mi,ci)){if(!tutorialAllows('boardSelect',{card:c,targetSide})){tutorialReject('boardSelect');return}if(state.boardSelected.has(c.uid))state.boardSelected.clear();else{state.boardSelected.clear();state.boardSelected.add(c.uid)}renderMelds();updateButtons()}"
text=rep(text,old,new,'recovery board selection gate')

# Tutorial button enablement for recover/maintenance.
old="attachBtn.disabled=!attachAllowed;recoverBtn.disabled=true;mb.disabled=true;document.getElementById('discardBtn').disabled=document.getElementById('discardBtn').disabled||!discardAllowed;"
new="attachBtn.disabled=!attachAllowed;recoverBtn.disabled=!rp||!tutorialAllows('recover',{plan:rp});mb.disabled=mb.disabled||!tutorialAllows('maintenance',{cards:cs});document.getElementById('discardBtn').disabled=document.getElementById('discardBtn').disabled||!discardAllowed;"
text=rep(text,old,new,'advanced tutorial button enablement')

# Advanced start button handler.
old="document.getElementById('practiceStartBtn').onclick=startPracticeBattle;"
new="document.getElementById('practiceStartBtn').onclick=startPracticeBattle;document.getElementById('advancedTutorialBtn').onclick=startAdvancedTutorial;"
text=rep(text,old,new,'advanced button handler')

# Roadmap: first half of P3 live, joker remains.
old="- [ ] 회수 / 정비 / 공식 상태 / 조커 고급 튜토리얼"
new="- [x] 회수 / 정비 / 공식 상태 고급 튜토리얼 — 기본 튜토리얼과 분리된 고급 진입. 실제 RUN 회수·체인 -1, 1장 정비 교체, 취약 1의 다음 폭발 +25% 및 소모를 고정 시나리오로 체험\n- [ ] 조커 고급 튜토리얼"
road=rep(road,old,new,'P3 roadmap split')

index.write_text(text,encoding='utf-8')
roadmap.write_text(road,encoding='utf-8')

# Regression test.
(root/'tests'/'tutorial-advanced-basics.mjs').write_text(r'''import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const road=fs.readFileSync(new URL('../ROADMAP.md',import.meta.url),'utf8');
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
function ok(v,m){if(!v)throw new Error(m);console.log(`PASS: ${m}`)}
new Function(script);
ok(html.includes('id="advancedTutorialBtn"')&&html.includes('고급 튜토리얼 · 기본 완료 후'),'start screen exposes a locked advanced tutorial entry');
ok(script.includes("function startAdvancedTutorial(){if(!progress.tutorialCompleted")&&script.includes("startTutorial('recover')"),'advanced tutorial is gated by basic completion and starts at recover');
ok(script.includes("{id:'rummy'")&&script.includes("completeOn:'rummy',stopAfter:true"),'basic tutorial still stops after RUMMY');
for(const id of ['recover','maintenance','status'])ok(script.includes(`{id:'${id}'`),`advanced tutorial registers ${id}`);
ok(script.includes("scenario:'recover'")&&script.includes("makeTutorialMeld('player','RUN'")&&script.includes("makeTutorialCard('C','7','recoverCard','player')"),'recover scenario uses a real four-card RUN with a designated recoverable end');
ok(script.includes("scenario:'maintenance'")&&script.includes("makeTutorialCard('C','Q','maintenanceSwap')")&&script.includes("makeTutorialCard('S','A','maintenanceDraw')"),'maintenance scenario deterministically swaps Q clubs into A spades');
ok(script.includes("applyOfficialStatus('player',p,'vulnerable',1,{silent:true})")&&script.includes("state.switchPower=8"),'status scenario uses the official vulnerable engine with a fixed bomb');
ok(script.includes("tutorialAllows('boardSelect',{card:c,targetSide})")&&script.includes("tutorialCheckProgress('recover',{card:c,targetSide:plan.side,beforeChain,afterChain:m.chain||0})"),'recover action is gated and completed through the real playerRecover path');
ok(script.includes("tutorialAllows('maintenance',{cards:cs})")&&script.includes("tutorialCheckProgress('maintenance',{sent:cs,got})"),'maintenance action is gated and completed through the real playerMaintenance path');
ok(script.includes("beforeVulnerable:tutorialBefore.vulnerable")&&script.includes("afterVulnerable:officialStatusValue('player',s,'vulnerable')"),'DETONATE tutorial context observes vulnerable consumption');
ok(script.includes("expectDamage!=null&&context.dealt!==step.expectDamage")&&script.includes('expectVulnerableConsumed'),'tutorial completion checks actual status damage and lifecycle consumption');
ok(script.includes("function tutorialSegmentInfo")&&script.includes("label:'고급 튜토리얼'"),'tutorial badge counts basic and advanced segments independently');
ok(script.includes("recoverBtn.disabled=!rp||!tutorialAllows('recover',{plan:rp})")&&script.includes("!tutorialAllows('maintenance',{cards:cs})"),'tutorial UI only enables recover and maintenance in their lessons');
ok(road.includes('- [x] 회수 / 정비 / 공식 상태 고급 튜토리얼')&&road.includes('- [ ] 조커 고급 튜토리얼'),'roadmap closes advanced basics while leaving Joker tutorial open');
console.log('RUMMY//DUEL advanced tutorial basics regressions passed.');
''',encoding='utf-8')
print('patched advanced tutorial basics')
