from pathlib import Path
p=Path('index.html')
s=p.read_text()

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing pattern: {label}')
    s=s.replace(old,new,1)

rep(" {id:'attachOwn',title:'붙이기',goal:'이미 공개된 내 조합에 조건이 맞는 카드를 붙입니다.',hint:'실제 attachCards 경로를 사용합니다.',implemented:false},\n {id:'attachEnemy',title:'상대 조합 이용',goal:'조건이 맞으면 상대 공개 조합에도 카드를 붙일 수 있습니다.',hint:'상대 공개 조합 이용은 핵심 규칙입니다.',implemented:false},\n {id:'switch',title:'스위치',goal:'버스트·체인으로 스위치를 상대에게 넘기는 과정을 체험합니다.',hint:'한 턴 기본 반환은 1회입니다.',implemented:false},",
" {id:'attachOwn',title:'붙이기',goal:'이미 공개된 내 런에 조건이 맞는 카드를 붙여 체인을 발생시킵니다.',hint:'강조된 7♣를 선택한 뒤 내 런에 붙이세요. 런은 붙일 때마다 체인 위력이 증가합니다.',implemented:true,scenario:'attachOwn',allow:['select','attach','clear'],selectRoles:['attachOwnCard'],attachSide:'player',expectAttach:'RUN',completeOn:'attach'},\n {id:'attachEnemy',title:'상대 조합 이용',goal:'조건이 맞으면 상대 공개 조합에도 내 카드를 붙일 수 있습니다.',hint:'강조된 8♥를 상대의 5♥-6♥-7♥ 런에 붙여 스위치를 돌려보내세요.',implemented:true,scenario:'attachEnemy',allow:['select','attach','clear'],selectRoles:['attachEnemyCard'],attachSide:'enemy',expectAttach:'RUN',completeOn:'attach'},\n {id:'switch',title:'스위치',goal:'나를 향한 스위치를 버스트로 상대에게 넘기고 누적 위력이 커지는 것을 확인합니다.',hint:'8♣를 내 8 세트에 붙이면 버스트 +24가 더해지고 스위치가 상대에게 넘어갑니다.',implemented:true,scenario:'switch',allow:['select','attach','clear'],selectRoles:['switchCard'],attachSide:'player',expectAttach:'SET',expectSwitchTarget:'enemy',minPowerGain:24,completeOn:'attach'},",
"tutorial step definitions")

rep("function tutorialAllows(action,context={}){if(state.sessionMode!=='tutorial')return true;const step=currentTutorialStep();if(!step||!step.implemented||!Array.isArray(step.allow)||!step.allow.includes(action))return false;if(action==='select'&&step.selectRoles?.length&&!step.selectRoles.includes(context.card?.tutorialRole))return false;if(action==='discard'&&step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;if(action==='meld'&&step.expectMeld&&context.type!==step.expectMeld)return false;return true}",
"function tutorialAllows(action,context={}){if(state.sessionMode!=='tutorial')return true;const step=currentTutorialStep();if(!step||!step.implemented||!Array.isArray(step.allow)||!step.allow.includes(action))return false;if(action==='select'&&step.selectRoles?.length&&!step.selectRoles.includes(context.card?.tutorialRole))return false;if(action==='discard'&&step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;if(action==='meld'&&step.expectMeld&&context.type!==step.expectMeld)return false;if(action==='attach'){if(step.attachSide&&context.targetSide!==step.attachSide)return false;if(step.expectAttach&&context.type!==step.expectAttach)return false}return true}",
"tutorial attach gate")

rep("function makeTutorialCard(suit,rank,role){const c=makeCard(suit,rank,false,'player');c.tutorialRole=role;return c}",
"function makeTutorialCard(suit,rank,role,owner='player'){const c=makeCard(suit,rank,false,owner);c.tutorialRole=role;return c}\nfunction makeTutorialMeld(owner,type,cards,chain=0){return{type,cards,chain,createdTurn:0,createdToken:state.turnToken-1,lastAttachToken:null,extraAttachGrantedToken:null,lastTouchedOwnerStart:0,status:blankMeldStatus()}}",
"tutorial card and meld helpers")

rep("else if(step.scenario==='run'){p.hand=[makeTutorialCard('C','4','runCard'),makeTutorialCard('C','5','runCard'),makeTutorialCard('C','6','runCard'),makeTutorialCard('D','9','hold')];state.phase='action';log('런 실습 · 4♣ · 5♣ · 6♣를 골라 새 런을 만드세요.','important')}return true}",
"else if(step.scenario==='run'){p.hand=[makeTutorialCard('C','4','runCard'),makeTutorialCard('C','5','runCard'),makeTutorialCard('C','6','runCard'),makeTutorialCard('D','9','hold')];state.phase='action';log('런 실습 · 4♣ · 5♣ · 6♣를 골라 새 런을 만드세요.','important')}else if(step.scenario==='attachOwn'){p.hand=[makeTutorialCard('C','7','attachOwnCard'),makeTutorialCard('D','2','hold')];p.melds=[makeTutorialMeld('player','RUN',[makeTutorialCard('C','4','board','player'),makeTutorialCard('C','5','board','player'),makeTutorialCard('C','6','board','player')])];state.phase='action';log('붙이기 실습 · 7♣를 내 4♣-5♣-6♣ 런에 붙이세요.','important')}else if(step.scenario==='attachEnemy'){p.hand=[makeTutorialCard('H','8','attachEnemyCard'),makeTutorialCard('S','2','hold')];e.melds=[makeTutorialMeld('enemy','RUN',[makeTutorialCard('H','5','board','enemy'),makeTutorialCard('H','6','board','enemy'),makeTutorialCard('H','7','board','enemy')])];state.switchTarget='player';state.switchPower=12;state.phase='action';log('상대 조합 실습 · 8♥를 상대 런에 붙여 스위치를 상대에게 반환하세요.','important')}else if(step.scenario==='switch'){p.hand=[makeTutorialCard('C','8','switchCard'),makeTutorialCard('D','2','hold')];p.melds=[makeTutorialMeld('player','SET',[makeTutorialCard('S','8','board','player'),makeTutorialCard('H','8','board','player'),makeTutorialCard('D','8','board','player')])];state.switchTarget='player';state.switchPower=36;state.phase='action';log('스위치 실습 · 8♣를 세트에 붙여 버스트 +24로 누적 위력을 키우고 상대에게 넘기세요.','important')}return true}",
"tutorial attach scenarios")

rep("function tutorialCheckProgress(event,context={}){if(state.sessionMode!=='tutorial')return false;const step=currentTutorialStep();if(!step?.completeOn||step.completeOn!==event)return false;if(step.expectMeld&&context.type!==step.expectMeld)return false;if(step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;const next=TUTORIAL_STEPS[tutorialStepIndex()+1];state.tutorialHintOpen=true;state.tutorialSuccessText=event==='discard'?'좋아요. 카드를 뽑고 선택해 버리는 기본 흐름을 익혔습니다.':`${step.title} 완성! 실제 조합 판정 엔진이 성공을 확인했습니다.`;log(`튜토리얼 ${step.title} 성공.`,'good');if(next?.implemented){render();renderTutorialCoach();const battleId=state.battleId,stepId=step.id;setTimeout(()=>{if(state.sessionMode==='tutorial'&&state.battleId===battleId&&state.tutorialStep===stepId)setTutorialStep(next.id)},650);return true}state.tutorialSegmentDone=true;render();renderTutorialCoach();return true}",
"function tutorialCheckProgress(event,context={}){if(state.sessionMode!=='tutorial')return false;const step=currentTutorialStep();if(!step?.completeOn||step.completeOn!==event)return false;if(step.expectMeld&&context.type!==step.expectMeld)return false;if(step.discardRole&&context.card?.tutorialRole!==step.discardRole)return false;if(step.attachSide&&context.targetSide!==step.attachSide)return false;if(step.expectAttach&&context.type!==step.expectAttach)return false;if(step.expectSwitchTarget&&context.afterTarget!==step.expectSwitchTarget)return false;if(step.minPowerGain&&((context.afterPower||0)-(context.beforePower||0)<step.minPowerGain))return false;const next=TUTORIAL_STEPS[tutorialStepIndex()+1];state.tutorialHintOpen=true;state.tutorialSuccessText=event==='discard'?'좋아요. 카드를 뽑고 선택해 버리는 기본 흐름을 익혔습니다.':event==='attach'?step.id==='attachEnemy'?'상대 공개 조합도 내 공격 경로로 사용할 수 있습니다.':step.id==='switch'?`버스트 성공! 누적 위력 ${context.beforePower} → ${context.afterPower}, 스위치가 상대에게 넘어갔습니다.`:`붙이기 성공! 실제 체인 처리로 누적 위력 ${context.afterPower}이 만들어졌습니다.`:`${step.title} 완성! 실제 조합 판정 엔진이 성공을 확인했습니다.`;log(`튜토리얼 ${step.title} 성공.`,'good');if(next?.implemented){render();renderTutorialCoach();const battleId=state.battleId,stepId=step.id;setTimeout(()=>{if(state.sessionMode==='tutorial'&&state.battleId===battleId&&state.tutorialStep===stepId)setTutorialStep(next.id)},800);return true}state.tutorialSegmentDone=true;render();renderTutorialCoach();return true}",
"tutorial attach progress")

rep("function renderTutorialHighlights(){for(const el of document.querySelectorAll('.tutorialTarget,.tutorialLocked'))el.classList.remove('tutorialTarget','tutorialLocked');if(state.sessionMode!=='tutorial')return;const step=currentTutorialStep();if(!step?.implemented)return;if(step.id==='basic'&&state.phase==='draw')document.getElementById('deckPile')?.classList.add('tutorialTarget');for(const c of state.player.hand){const el=document.querySelector(`.cardBtn[data-uid=\"${c.uid}\"]`);if(!el)continue;if(tutorialAllows('select',{card:c}))el.classList.add('tutorialTarget');else el.classList.add('tutorialLocked')}const cs=selectedCards(),t=cs.length===3?meldType(cs):null;if(tutorialAllows('meld',{cards:cs,type:t})&&cs.length===3)document.getElementById('meldBtn')?.classList.add('tutorialTarget');if(cs.length===1&&tutorialAllows('discard',{card:cs[0]}))document.getElementById('discardBtn')?.classList.add('tutorialTarget')}",
"function renderTutorialHighlights(){for(const el of document.querySelectorAll('.tutorialTarget,.tutorialLocked'))el.classList.remove('tutorialTarget','tutorialLocked');if(state.sessionMode!=='tutorial')return;const step=currentTutorialStep();if(!step?.implemented)return;if(step.id==='basic'&&state.phase==='draw')document.getElementById('deckPile')?.classList.add('tutorialTarget');for(const c of state.player.hand){const el=document.querySelector(`.cardBtn[data-uid=\"${c.uid}\"]`);if(!el)continue;if(tutorialAllows('select',{card:c}))el.classList.add('tutorialTarget');else el.classList.add('tutorialLocked')}const cs=selectedCards(),t=cs.length===3?meldType(cs):null;if(tutorialAllows('meld',{cards:cs,type:t})&&cs.length===3)document.getElementById('meldBtn')?.classList.add('tutorialTarget');if(cs.length===1&&tutorialAllows('discard',{card:cs[0]}))document.getElementById('discardBtn')?.classList.add('tutorialTarget');if(step.allow?.includes('attach')){const side=step.attachSide||'player',m=meldsOf(side)[0],type=m?.type;const entry=document.querySelector(`.meldEntry[data-side=\"${side}\"][data-index=\"0\"]`);if(entry)entry.classList.add('tutorialTarget');if(cs.length&&tutorialAllows('attach',{cards:cs,targetSide:side,targetIndex:0,type})&&canAttachTo(side,0,cs))document.querySelector(`.attachHereBtn[data-attach-side=\"${side}\"][data-attach-index=\"0\"]`)?.classList.add('tutorialTarget')}}",
"tutorial attach highlights")

rep("function playerAttach(){if(state.turn!=='player'||state.phase!=='action')return;const cs=selectedCards();if(!cs.length){log('붙일 손패 카드를 선택하세요.','hit');return}let target=state.target;if(!target){const cand=attachCandidates(cs);if(cand.length===1)target={side:cand[0].side,index:cand[0].index};else{log(cand.length?'붙일 곳이 여러 곳입니다. 공개 조합 아래의 붙이기 버튼을 고르세요.':'붙일 수 있는 공개 조합이 없습니다.','hit');return}}const ok=attachCards('player',cs,target.side,target.index);if(!ok){log('붙이기 불가 · 같은 조합에 이번 턴 이미 붙였거나, 붙인 뒤 조합이 유효하지 않습니다.','hit');return}state.selected.clear();state.selectionOrder=[];state.boardSelected.clear();state.target=null;render()}",
"function playerAttach(){if(state.turn!=='player'||state.phase!=='action')return;const cs=selectedCards();if(!cs.length){log('붙일 손패 카드를 선택하세요.','hit');return}let target=state.target;if(!target){const cand=attachCandidates(cs);if(cand.length===1)target={side:cand[0].side,index:cand[0].index};else{log(cand.length?'붙일 곳이 여러 곳입니다. 공개 조합 아래의 붙이기 버튼을 고르세요.':'붙일 수 있는 공개 조합이 없습니다.','hit');return}}const m=meldsOf(target.side)[target.index],type=m?.type;if(!tutorialAllows('attach',{cards:cs,targetSide:target.side,targetIndex:target.index,type})){tutorialReject('attach');return}const beforePower=state.switchPower,beforeTarget=state.switchTarget;const ok=attachCards('player',cs,target.side,target.index);if(!ok){log('붙이기 불가 · 같은 조합에 이번 턴 이미 붙였거나, 붙인 뒤 조합이 유효하지 않습니다.','hit');return}state.selected.clear();state.selectionOrder=[];state.boardSelected.clear();state.target=null;if(tutorialCheckProgress('attach',{cards:cs,targetSide:target.side,targetIndex:target.index,type,beforePower,beforeTarget,afterPower:state.switchPower,afterTarget:state.switchTarget}))return;render()}",
"player attach tutorial hook")

rep("attachBtn.disabled=true;recoverBtn.disabled=true;mb.disabled=true;document.getElementById('discardBtn').disabled=document.getElementById('discardBtn').disabled||!discardAllowed;",
"const attachAllowed=state.target?!!preview&&tutorialAllows('attach',{cards:cs,targetSide:state.target.side,targetIndex:state.target.index,type:meldsOf(state.target.side)[state.target.index]?.type}):cand.some(x=>tutorialAllows('attach',{cards:cs,targetSide:x.side,targetIndex:x.index,type:x.m.type}));attachBtn.disabled=!attachAllowed;recoverBtn.disabled=true;mb.disabled=true;document.getElementById('discardBtn').disabled=document.getElementById('discardBtn').disabled||!discardAllowed;",
"tutorial attach button state")

p.write_text(s)

rp=Path('ROADMAP.md')
r=rp.read_text()
old='- [ ] 붙이기 튜토리얼\n- [ ] 상대 공개 조합 붙이기 체험\n- [ ] 스위치 튜토리얼'
new='- [x] 붙이기 튜토리얼 — 고정 내 RUN에 실제 `attachCards` 체인 붙이기\n- [x] 상대 공개 조합 붙이기 체험 — 고정 상대 RUN에 내 카드 붙이기 + 실제 스위치 반환\n- [x] 스위치 튜토리얼 — 나를 향한 누적 36에서 4번째 8로 버스트 +24, 상대에게 스위치 반환 확인'
if old not in r: raise SystemExit('missing roadmap tutorial checkboxes')
r=r.replace(old,new,1)
oldnext='1. UX1 P1: deterministic 기본 조작 → 세트 → 런 lessons are live; next connect 붙이기 → 상대 공개 조합 → 스위치 → 러미 to the same real-engine tutorial controller.'
newnext='1. UX1 P1: deterministic 기본 조작 → 세트 → 런 → 붙이기 → 상대 공개 조합 → 스위치 lessons are live; next connect 러미, then move into P2 누적 위력 / 폭발 tutorial.'
if oldnext not in r: raise SystemExit('missing roadmap current next work')
r=r.replace(oldnext,newnext,1)
rp.write_text(r)

t=Path('tests/tutorial-attach-switch.mjs')
t.write_text("""import fs from 'node:fs';\n\nconst html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');\nconst roadmap = fs.readFileSync(new URL('../ROADMAP.md', import.meta.url), 'utf8');\nconst script = [...html.matchAll(/<script>([\\s\\S]*?)<\\/script>/g)].map(m => m[1]).join('\\n');\n\nfunction ok(condition, message) { if (!condition) throw new Error(message); console.log(`PASS: ${message}`); }\nnew Function(script);\n\nok(script.includes(\"id:'attachOwn'\") && script.includes(\"scenario:'attachOwn'\") && script.includes(\"attachSide:'player'\") && script.includes(\"expectAttach:'RUN'\"), 'own-attach lesson is implemented as a real RUN attach scenario');\nok(script.includes(\"makeTutorialCard('C','7','attachOwnCard')\") && script.includes(\"makeTutorialMeld('player','RUN'\"), 'own-attach lesson fixes a 4-5-6 club RUN plus 7 club');\nok(script.includes(\"id:'attachEnemy'\") && script.includes(\"attachSide:'enemy'\") && script.includes(\"makeTutorialCard('H','8','attachEnemyCard')\") && script.includes(\"makeTutorialMeld('enemy','RUN'\"), 'opponent-attach lesson uses a fixed enemy heart RUN');\nok(script.includes(\"state.switchTarget='player';state.switchPower=12\"), 'opponent-attach lesson begins with SWITCH on the player so a legal return can be experienced');\nok(script.includes(\"id:'switch'\") && script.includes(\"expectAttach:'SET'\") && script.includes(\"expectSwitchTarget:'enemy'\") && script.includes(\"minPowerGain:24\"), 'SWITCH lesson requires a real SET BURST return and minimum +24 gain');\nok(script.includes(\"state.switchTarget='player';state.switchPower=36\") && script.includes(\"makeTutorialCard('C','8','switchCard')\") && script.includes(\"makeTutorialMeld('player','SET'\"), 'SWITCH lesson fixes a threatened 3SET and fourth-suit completion card');\nok(script.includes(\"if(!tutorialAllows('attach',{cards:cs,targetSide:target.side,targetIndex:target.index,type}))\"), 'playerAttach is mutation-gated by the tutorial contract');\nok(script.includes(\"const beforePower=state.switchPower,beforeTarget=state.switchTarget;const ok=attachCards('player',cs,target.side,target.index)\"), 'tutorial attach success still runs through the real attachCards path');\nok(script.includes(\"tutorialCheckProgress('attach',{cards:cs,targetSide:target.side\") && script.includes(\"afterPower:state.switchPower,afterTarget:state.switchTarget\"), 'tutorial completion checks the actual resulting SWITCH state and power');\nok(script.includes(\"entry.classList.add('tutorialTarget')\") && script.includes(\".attachHereBtn[data-attach-side=\\\"${side}\\\"]\"), 'tutorial highlights the intended meld and real attach button');\nok(roadmap.includes('- [x] 붙이기 튜토리얼') && roadmap.includes('- [x] 상대 공개 조합 붙이기 체험') && roadmap.includes('- [x] 스위치 튜토리얼'), 'UX1 roadmap records attach/opponent/SWITCH lessons complete');\n\nconsole.log('RUMMY//DUEL deterministic attach/opponent/SWITCH tutorial regressions passed.');\n""")
